### ISSUE TITLE
크롤 대상 커뮤니티 리서치

### ISSUE THREAD

**Issue by iamminji** [getaraise/visi-spidey#1]
크롤할 [커뮤니티 사이트](https://namu.wiki/w/%EC%9D%B8%ED%84%B0%EB%84%B7%20%EA%B4%80%EB%A0%A8%20%EC%A0%95%EB%B3%B4#s-3.1.3) 정하기

**Comment by kiyeoneee** [comment]
클리앙
보배드림
인벤
오유
더쿠
인스티즈

**Comment by kiyeoneee** [comment]
베스트 게시판 (보배드림 기준)
- page 2~3 depth까지 크롤링
- 크롤링 내용 : title, url, 조회수, 게시판, 등록일, 크롤링하는 시점의 시간

**Comment by iamminji** [comment]
리서치는 종료하겠습니다.
